// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vasystem/api/v2/airlines.proto
#ifndef GRPC_vasystem_2fapi_2fv2_2fairlines_2eproto__INCLUDED
#define GRPC_vasystem_2fapi_2fv2_2fairlines_2eproto__INCLUDED

#include "vasystem/api/v2/airlines.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vasystem {
namespace api {
namespace v2 {

// Retrieve airline information.
class AirlinesService final {
 public:
  static constexpr char const* service_full_name() {
    return "vasystem.api.v2.AirlinesService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // List airlines
    virtual ::grpc::Status ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::vasystem::api::v2::ListAirlinesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>> AsyncListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>>(AsyncListAirlinesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>> PrepareAsyncListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>>(PrepareAsyncListAirlinesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // List airlines
      virtual void ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>* AsyncListAirlinesRaw(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vasystem::api::v2::ListAirlinesResponse>* PrepareAsyncListAirlinesRaw(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::vasystem::api::v2::ListAirlinesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>> AsyncListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>>(AsyncListAirlinesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>> PrepareAsyncListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>>(PrepareAsyncListAirlinesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response, std::function<void(::grpc::Status)>) override;
      void ListAirlines(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>* AsyncListAirlinesRaw(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vasystem::api::v2::ListAirlinesResponse>* PrepareAsyncListAirlinesRaw(::grpc::ClientContext* context, const ::vasystem::api::v2::ListAirlinesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListAirlines_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // List airlines
    virtual ::grpc::Status ListAirlines(::grpc::ServerContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListAirlines() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAirlines(::grpc::ServerContext* context, ::vasystem::api::v2::ListAirlinesRequest* request, ::grpc::ServerAsyncResponseWriter< ::vasystem::api::v2::ListAirlinesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListAirlines<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListAirlines() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vasystem::api::v2::ListAirlinesRequest, ::vasystem::api::v2::ListAirlinesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vasystem::api::v2::ListAirlinesRequest* request, ::vasystem::api::v2::ListAirlinesResponse* response) { return this->ListAirlines(context, request, response); }));}
    void SetMessageAllocatorFor_ListAirlines(
        ::grpc::MessageAllocator< ::vasystem::api::v2::ListAirlinesRequest, ::vasystem::api::v2::ListAirlinesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vasystem::api::v2::ListAirlinesRequest, ::vasystem::api::v2::ListAirlinesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAirlines(
      ::grpc::CallbackServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListAirlines<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListAirlines() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListAirlines() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAirlines(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListAirlines() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListAirlines(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAirlines(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListAirlines : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListAirlines() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vasystem::api::v2::ListAirlinesRequest, ::vasystem::api::v2::ListAirlinesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vasystem::api::v2::ListAirlinesRequest, ::vasystem::api::v2::ListAirlinesResponse>* streamer) {
                       return this->StreamedListAirlines(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListAirlines() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListAirlines(::grpc::ServerContext* /*context*/, const ::vasystem::api::v2::ListAirlinesRequest* /*request*/, ::vasystem::api::v2::ListAirlinesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListAirlines(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vasystem::api::v2::ListAirlinesRequest,::vasystem::api::v2::ListAirlinesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListAirlines<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListAirlines<Service > StreamedService;
};

}  // namespace v2
}  // namespace api
}  // namespace vasystem


#endif  // GRPC_vasystem_2fapi_2fv2_2fairlines_2eproto__INCLUDED
