// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/airports.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vasystem_2fapi_2fv2_2fairports_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vasystem_2fapi_2fv2_2fairports_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021007 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vasystem_2fapi_2fv2_2fairports_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vasystem_2fapi_2fv2_2fairports_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vasystem_2fapi_2fv2_2fairports_2eproto;
namespace vasystem {
namespace api {
namespace v2 {
class Airport;
struct AirportDefaultTypeInternal;
extern AirportDefaultTypeInternal _Airport_default_instance_;
}  // namespace v2
}  // namespace api
}  // namespace vasystem
PROTOBUF_NAMESPACE_OPEN
template<> ::vasystem::api::v2::Airport* Arena::CreateMaybeMessage<::vasystem::api::v2::Airport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vasystem {
namespace api {
namespace v2 {

// ===================================================================

class Airport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vasystem.api.v2.Airport) */ {
 public:
  inline Airport() : Airport(nullptr) {}
  ~Airport() override;
  explicit PROTOBUF_CONSTEXPR Airport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Airport(const Airport& from);
  Airport(Airport&& from) noexcept
    : Airport() {
    *this = ::std::move(from);
  }

  inline Airport& operator=(const Airport& from) {
    CopyFrom(from);
    return *this;
  }
  inline Airport& operator=(Airport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Airport& default_instance() {
    return *internal_default_instance();
  }
  static inline const Airport* internal_default_instance() {
    return reinterpret_cast<const Airport*>(
               &_Airport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Airport& a, Airport& b) {
    a.Swap(&b);
  }
  inline void Swap(Airport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Airport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Airport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Airport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Airport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Airport& from) {
    Airport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Airport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vasystem.api.v2.Airport";
  }
  protected:
  explicit Airport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kIcaoCodeFieldNumber = 2,
    kIataCodeFieldNumber = 3,
  };
  // string id = 1 [json_name = "id"];
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string icao_code = 2 [json_name = "icaoCode"];
  void clear_icao_code();
  const std::string& icao_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_icao_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_icao_code();
  PROTOBUF_NODISCARD std::string* release_icao_code();
  void set_allocated_icao_code(std::string* icao_code);
  private:
  const std::string& _internal_icao_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_icao_code(const std::string& value);
  std::string* _internal_mutable_icao_code();
  public:

  // string iata_code = 3 [json_name = "iataCode"];
  void clear_iata_code();
  const std::string& iata_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_iata_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_iata_code();
  PROTOBUF_NODISCARD std::string* release_iata_code();
  void set_allocated_iata_code(std::string* iata_code);
  private:
  const std::string& _internal_iata_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iata_code(const std::string& value);
  std::string* _internal_mutable_iata_code();
  public:

  // @@protoc_insertion_point(class_scope:vasystem.api.v2.Airport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icao_code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr iata_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vasystem_2fapi_2fv2_2fairports_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Airport

// string id = 1 [json_name = "id"];
inline void Airport::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& Airport::id() const {
  // @@protoc_insertion_point(field_get:vasystem.api.v2.Airport.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Airport::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vasystem.api.v2.Airport.id)
}
inline std::string* Airport::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:vasystem.api.v2.Airport.id)
  return _s;
}
inline const std::string& Airport::_internal_id() const {
  return _impl_.id_.Get();
}
inline void Airport::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* Airport::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* Airport::release_id() {
  // @@protoc_insertion_point(field_release:vasystem.api.v2.Airport.id)
  return _impl_.id_.Release();
}
inline void Airport::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vasystem.api.v2.Airport.id)
}

// string icao_code = 2 [json_name = "icaoCode"];
inline void Airport::clear_icao_code() {
  _impl_.icao_code_.ClearToEmpty();
}
inline const std::string& Airport::icao_code() const {
  // @@protoc_insertion_point(field_get:vasystem.api.v2.Airport.icao_code)
  return _internal_icao_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Airport::set_icao_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.icao_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vasystem.api.v2.Airport.icao_code)
}
inline std::string* Airport::mutable_icao_code() {
  std::string* _s = _internal_mutable_icao_code();
  // @@protoc_insertion_point(field_mutable:vasystem.api.v2.Airport.icao_code)
  return _s;
}
inline const std::string& Airport::_internal_icao_code() const {
  return _impl_.icao_code_.Get();
}
inline void Airport::_internal_set_icao_code(const std::string& value) {
  
  _impl_.icao_code_.Set(value, GetArenaForAllocation());
}
inline std::string* Airport::_internal_mutable_icao_code() {
  
  return _impl_.icao_code_.Mutable(GetArenaForAllocation());
}
inline std::string* Airport::release_icao_code() {
  // @@protoc_insertion_point(field_release:vasystem.api.v2.Airport.icao_code)
  return _impl_.icao_code_.Release();
}
inline void Airport::set_allocated_icao_code(std::string* icao_code) {
  if (icao_code != nullptr) {
    
  } else {
    
  }
  _impl_.icao_code_.SetAllocated(icao_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.icao_code_.IsDefault()) {
    _impl_.icao_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vasystem.api.v2.Airport.icao_code)
}

// string iata_code = 3 [json_name = "iataCode"];
inline void Airport::clear_iata_code() {
  _impl_.iata_code_.ClearToEmpty();
}
inline const std::string& Airport::iata_code() const {
  // @@protoc_insertion_point(field_get:vasystem.api.v2.Airport.iata_code)
  return _internal_iata_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Airport::set_iata_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.iata_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vasystem.api.v2.Airport.iata_code)
}
inline std::string* Airport::mutable_iata_code() {
  std::string* _s = _internal_mutable_iata_code();
  // @@protoc_insertion_point(field_mutable:vasystem.api.v2.Airport.iata_code)
  return _s;
}
inline const std::string& Airport::_internal_iata_code() const {
  return _impl_.iata_code_.Get();
}
inline void Airport::_internal_set_iata_code(const std::string& value) {
  
  _impl_.iata_code_.Set(value, GetArenaForAllocation());
}
inline std::string* Airport::_internal_mutable_iata_code() {
  
  return _impl_.iata_code_.Mutable(GetArenaForAllocation());
}
inline std::string* Airport::release_iata_code() {
  // @@protoc_insertion_point(field_release:vasystem.api.v2.Airport.iata_code)
  return _impl_.iata_code_.Release();
}
inline void Airport::set_allocated_iata_code(std::string* iata_code) {
  if (iata_code != nullptr) {
    
  } else {
    
  }
  _impl_.iata_code_.SetAllocated(iata_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.iata_code_.IsDefault()) {
    _impl_.iata_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vasystem.api.v2.Airport.iata_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v2
}  // namespace api
}  // namespace vasystem

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vasystem_2fapi_2fv2_2fairports_2eproto
