# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vasystem/api/v2/airlines.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vasystem/api/v2/airlines.proto", :syntax => :proto3) do
    add_message "vasystem.api.v2.ListAirlinesRequest" do
    end
    add_message "vasystem.api.v2.ListAirlinesResponse" do
      repeated :airlines, :message, 1, "vasystem.api.v2.Airline", json_name: "airlines"
    end
    add_message "vasystem.api.v2.Airline" do
      optional :id, :string, 1, json_name: "id"
      optional :icao_code, :string, 2, json_name: "icaoCode"
      optional :iata_code, :string, 3, json_name: "iataCode"
      optional :display_icao_code, :string, 4, json_name: "displayIcaoCode"
      optional :display_iata_code, :string, 5, json_name: "displayIataCode"
      optional :name, :string, 6, json_name: "name"
    end
  end
end

module Vasystem
  module Api
    module V2
      ListAirlinesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vasystem.api.v2.ListAirlinesRequest").msgclass
      ListAirlinesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vasystem.api.v2.ListAirlinesResponse").msgclass
      Airline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vasystem.api.v2.Airline").msgclass
    end
  end
end
