# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vasystem/api/v2/dayofweek.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vasystem/api/v2/dayofweek.proto", :syntax => :proto3) do
    add_enum "vasystem.api.v2.DayOfWeek" do
      value :DAY_OF_WEEK_UNSPECIFIED, 0
      value :DAY_OF_WEEK_MONDAY, 1
      value :DAY_OF_WEEK_TUESDAY, 2
      value :DAY_OF_WEEK_WEDNESDAY, 3
      value :DAY_OF_WEEK_THURSDAY, 4
      value :DAY_OF_WEEK_FRIDAY, 5
      value :DAY_OF_WEEK_SATURDAY, 6
      value :DAY_OF_WEEK_SUNDAY, 7
    end
  end
end

module Vasystem
  module Api
    module V2
      DayOfWeek = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vasystem.api.v2.DayOfWeek").enummodule
    end
  end
end
