/* eslint-disable */
// @generated by protobuf-ts 2.8.1 with parameter long_type_string,ts_nocheck,eslint_disable
// @generated from protobuf file "vasystem/api/v2/airlines.proto" (package "vasystem.api.v2", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AirlinesService } from "./airlines";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListAirlinesResponse } from "./airlines";
import type { ListAirlinesRequest } from "./airlines";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service vasystem.api.v2.AirlinesService
 */
export interface IAirlinesServiceClient {
    /**
     * List airlines
     *
     * @generated from protobuf rpc: ListAirlines(vasystem.api.v2.ListAirlinesRequest) returns (vasystem.api.v2.ListAirlinesResponse);
     */
    listAirlines(input: ListAirlinesRequest, options?: RpcOptions): UnaryCall<ListAirlinesRequest, ListAirlinesResponse>;
}
/**
 * @generated from protobuf service vasystem.api.v2.AirlinesService
 */
export class AirlinesServiceClient implements IAirlinesServiceClient, ServiceInfo {
    typeName = AirlinesService.typeName;
    methods = AirlinesService.methods;
    options = AirlinesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * List airlines
     *
     * @generated from protobuf rpc: ListAirlines(vasystem.api.v2.ListAirlinesRequest) returns (vasystem.api.v2.ListAirlinesResponse);
     */
    listAirlines(input: ListAirlinesRequest, options?: RpcOptions): UnaryCall<ListAirlinesRequest, ListAirlinesResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAirlinesRequest, ListAirlinesResponse>("unary", this._transport, method, opt, input);
    }
}
