// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/aircraft.proto

package dev.vasystem.api.v2;

public final class AircraftProto {
  private AircraftProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vasystem_api_v2_AircraftType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vasystem_api_v2_AircraftType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vasystem_api_v2_AircraftModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vasystem_api_v2_AircraftModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036vasystem/api/v2/aircraft.proto\022\017vasyst" +
      "em.api.v2\032\036vasystem/api/v2/airlines.prot" +
      "o\"l\n\014AircraftType\022\016\n\002id\030\001 \001(\tR\002id\022\033\n\tica" +
      "o_code\030\002 \001(\tR\010icaoCode\022\033\n\tiata_code\030\003 \001(" +
      "\tR\010iataCode\022\022\n\004name\030\004 \001(\tR\004name\"\253\001\n\rAirc" +
      "raftModel\022\016\n\002id\030\001 \001(\tR\002id\022B\n\raircraft_ty" +
      "pe\030\002 \001(\0132\035.vasystem.api.v2.AircraftTypeR" +
      "\014aircraftType\0222\n\007airline\030\003 \001(\0132\030.vasyste" +
      "m.api.v2.AirlineR\007airline\022\022\n\004name\030\004 \001(\tR" +
      "\004nameB\271\001\n\023dev.vasystem.api.v2B\rAircraftP" +
      "rotoP\001Z5github.com/vasystem/api/grpc/go/" +
      "vasystem/api/v2;apiv2\242\002\003VAX\252\002\017Vasystem.A" +
      "pi.V2\312\002\017Vasystem\\Api\\V2\342\002\033Vasystem\\Api\\V" +
      "2\\GPBMetadata\352\002\021Vasystem::Api::V2b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.vasystem.api.v2.AirlinesProto.getDescriptor(),
        });
    internal_static_vasystem_api_v2_AircraftType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vasystem_api_v2_AircraftType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vasystem_api_v2_AircraftType_descriptor,
        new java.lang.String[] { "Id", "IcaoCode", "IataCode", "Name", });
    internal_static_vasystem_api_v2_AircraftModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vasystem_api_v2_AircraftModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vasystem_api_v2_AircraftModel_descriptor,
        new java.lang.String[] { "Id", "AircraftType", "Airline", "Name", });
    dev.vasystem.api.v2.AirlinesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
