// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/aircraft.proto

package dev.vasystem.api.v2;

/**
 * Protobuf type {@code vasystem.api.v2.AircraftType}
 */
public final class AircraftType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vasystem.api.v2.AircraftType)
    AircraftTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AircraftType.newBuilder() to construct.
  private AircraftType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AircraftType() {
    id_ = "";
    icaoCode_ = "";
    iataCode_ = "";
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AircraftType();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.vasystem.api.v2.AircraftProto.internal_static_vasystem_api_v2_AircraftType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.vasystem.api.v2.AircraftProto.internal_static_vasystem_api_v2_AircraftType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.vasystem.api.v2.AircraftType.class, dev.vasystem.api.v2.AircraftType.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICAO_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object icaoCode_;
  /**
   * <pre>
   * The ICAO aircraft type code.
   * </pre>
   *
   * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
   * @return The icaoCode.
   */
  @java.lang.Override
  public java.lang.String getIcaoCode() {
    java.lang.Object ref = icaoCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      icaoCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ICAO aircraft type code.
   * </pre>
   *
   * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
   * @return The bytes for icaoCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIcaoCodeBytes() {
    java.lang.Object ref = icaoCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      icaoCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IATA_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object iataCode_;
  /**
   * <pre>
   * The IATA aircraft type code.
   * </pre>
   *
   * <code>string iata_code = 3 [json_name = "iataCode"];</code>
   * @return The iataCode.
   */
  @java.lang.Override
  public java.lang.String getIataCode() {
    java.lang.Object ref = iataCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iataCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The IATA aircraft type code.
   * </pre>
   *
   * <code>string iata_code = 3 [json_name = "iataCode"];</code>
   * @return The bytes for iataCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIataCodeBytes() {
    java.lang.Object ref = iataCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iataCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(icaoCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, icaoCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iataCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iataCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(icaoCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, icaoCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iataCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iataCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.vasystem.api.v2.AircraftType)) {
      return super.equals(obj);
    }
    dev.vasystem.api.v2.AircraftType other = (dev.vasystem.api.v2.AircraftType) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getIcaoCode()
        .equals(other.getIcaoCode())) return false;
    if (!getIataCode()
        .equals(other.getIataCode())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + ICAO_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getIcaoCode().hashCode();
    hash = (37 * hash) + IATA_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getIataCode().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.vasystem.api.v2.AircraftType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.AircraftType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.AircraftType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.AircraftType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.vasystem.api.v2.AircraftType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vasystem.api.v2.AircraftType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vasystem.api.v2.AircraftType)
      dev.vasystem.api.v2.AircraftTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.vasystem.api.v2.AircraftProto.internal_static_vasystem_api_v2_AircraftType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.vasystem.api.v2.AircraftProto.internal_static_vasystem_api_v2_AircraftType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.vasystem.api.v2.AircraftType.class, dev.vasystem.api.v2.AircraftType.Builder.class);
    }

    // Construct using dev.vasystem.api.v2.AircraftType.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      icaoCode_ = "";

      iataCode_ = "";

      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.vasystem.api.v2.AircraftProto.internal_static_vasystem_api_v2_AircraftType_descriptor;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.AircraftType getDefaultInstanceForType() {
      return dev.vasystem.api.v2.AircraftType.getDefaultInstance();
    }

    @java.lang.Override
    public dev.vasystem.api.v2.AircraftType build() {
      dev.vasystem.api.v2.AircraftType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.AircraftType buildPartial() {
      dev.vasystem.api.v2.AircraftType result = new dev.vasystem.api.v2.AircraftType(this);
      result.id_ = id_;
      result.icaoCode_ = icaoCode_;
      result.iataCode_ = iataCode_;
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.vasystem.api.v2.AircraftType) {
        return mergeFrom((dev.vasystem.api.v2.AircraftType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.vasystem.api.v2.AircraftType other) {
      if (other == dev.vasystem.api.v2.AircraftType.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getIcaoCode().isEmpty()) {
        icaoCode_ = other.icaoCode_;
        onChanged();
      }
      if (!other.getIataCode().isEmpty()) {
        iataCode_ = other.iataCode_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              icaoCode_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              iataCode_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object icaoCode_ = "";
    /**
     * <pre>
     * The ICAO aircraft type code.
     * </pre>
     *
     * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
     * @return The icaoCode.
     */
    public java.lang.String getIcaoCode() {
      java.lang.Object ref = icaoCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        icaoCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ICAO aircraft type code.
     * </pre>
     *
     * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
     * @return The bytes for icaoCode.
     */
    public com.google.protobuf.ByteString
        getIcaoCodeBytes() {
      java.lang.Object ref = icaoCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icaoCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ICAO aircraft type code.
     * </pre>
     *
     * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
     * @param value The icaoCode to set.
     * @return This builder for chaining.
     */
    public Builder setIcaoCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      icaoCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ICAO aircraft type code.
     * </pre>
     *
     * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIcaoCode() {
      
      icaoCode_ = getDefaultInstance().getIcaoCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ICAO aircraft type code.
     * </pre>
     *
     * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
     * @param value The bytes for icaoCode to set.
     * @return This builder for chaining.
     */
    public Builder setIcaoCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      icaoCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object iataCode_ = "";
    /**
     * <pre>
     * The IATA aircraft type code.
     * </pre>
     *
     * <code>string iata_code = 3 [json_name = "iataCode"];</code>
     * @return The iataCode.
     */
    public java.lang.String getIataCode() {
      java.lang.Object ref = iataCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iataCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The IATA aircraft type code.
     * </pre>
     *
     * <code>string iata_code = 3 [json_name = "iataCode"];</code>
     * @return The bytes for iataCode.
     */
    public com.google.protobuf.ByteString
        getIataCodeBytes() {
      java.lang.Object ref = iataCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iataCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The IATA aircraft type code.
     * </pre>
     *
     * <code>string iata_code = 3 [json_name = "iataCode"];</code>
     * @param value The iataCode to set.
     * @return This builder for chaining.
     */
    public Builder setIataCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iataCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The IATA aircraft type code.
     * </pre>
     *
     * <code>string iata_code = 3 [json_name = "iataCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIataCode() {
      
      iataCode_ = getDefaultInstance().getIataCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The IATA aircraft type code.
     * </pre>
     *
     * <code>string iata_code = 3 [json_name = "iataCode"];</code>
     * @param value The bytes for iataCode to set.
     * @return This builder for chaining.
     */
    public Builder setIataCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iataCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vasystem.api.v2.AircraftType)
  }

  // @@protoc_insertion_point(class_scope:vasystem.api.v2.AircraftType)
  private static final dev.vasystem.api.v2.AircraftType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.vasystem.api.v2.AircraftType();
  }

  public static dev.vasystem.api.v2.AircraftType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AircraftType>
      PARSER = new com.google.protobuf.AbstractParser<AircraftType>() {
    @java.lang.Override
    public AircraftType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AircraftType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AircraftType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.vasystem.api.v2.AircraftType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

