// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/airports.proto

package dev.vasystem.api.v2;

public interface AirportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vasystem.api.v2.Airport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier of the airport.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The unique identifier of the airport.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The ICAO airport identifier. Unique.
   * </pre>
   *
   * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
   * @return The icaoCode.
   */
  java.lang.String getIcaoCode();
  /**
   * <pre>
   * The ICAO airport identifier. Unique.
   * </pre>
   *
   * <code>string icao_code = 2 [json_name = "icaoCode"];</code>
   * @return The bytes for icaoCode.
   */
  com.google.protobuf.ByteString
      getIcaoCodeBytes();

  /**
   * <pre>
   * The IATA airport identifier. This field is not unique.
   * </pre>
   *
   * <code>string iata_code = 3 [json_name = "iataCode"];</code>
   * @return The iataCode.
   */
  java.lang.String getIataCode();
  /**
   * <pre>
   * The IATA airport identifier. This field is not unique.
   * </pre>
   *
   * <code>string iata_code = 3 [json_name = "iataCode"];</code>
   * @return The bytes for iataCode.
   */
  com.google.protobuf.ByteString
      getIataCodeBytes();
}
