// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/virtual_airlines.proto

package dev.vasystem.api.v2;

/**
 * <pre>
 * The GetVirtualAirlineRequest message contains the request parameters for the
 * GetVirtualAirline method.
 * </pre>
 *
 * Protobuf type {@code vasystem.api.v2.GetVirtualAirlineRequest}
 */
public final class GetVirtualAirlineRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vasystem.api.v2.GetVirtualAirlineRequest)
    GetVirtualAirlineRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVirtualAirlineRequest.newBuilder() to construct.
  private GetVirtualAirlineRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVirtualAirlineRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetVirtualAirlineRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.vasystem.api.v2.VirtualAirlinesProto.internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.vasystem.api.v2.VirtualAirlinesProto.internal_static_vasystem_api_v2_GetVirtualAirlineRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.vasystem.api.v2.GetVirtualAirlineRequest.class, dev.vasystem.api.v2.GetVirtualAirlineRequest.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.vasystem.api.v2.GetVirtualAirlineRequest)) {
      return super.equals(obj);
    }
    dev.vasystem.api.v2.GetVirtualAirlineRequest other = (dev.vasystem.api.v2.GetVirtualAirlineRequest) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.GetVirtualAirlineRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.vasystem.api.v2.GetVirtualAirlineRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The GetVirtualAirlineRequest message contains the request parameters for the
   * GetVirtualAirline method.
   * </pre>
   *
   * Protobuf type {@code vasystem.api.v2.GetVirtualAirlineRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vasystem.api.v2.GetVirtualAirlineRequest)
      dev.vasystem.api.v2.GetVirtualAirlineRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.vasystem.api.v2.VirtualAirlinesProto.internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.vasystem.api.v2.VirtualAirlinesProto.internal_static_vasystem_api_v2_GetVirtualAirlineRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.vasystem.api.v2.GetVirtualAirlineRequest.class, dev.vasystem.api.v2.GetVirtualAirlineRequest.Builder.class);
    }

    // Construct using dev.vasystem.api.v2.GetVirtualAirlineRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.vasystem.api.v2.VirtualAirlinesProto.internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.GetVirtualAirlineRequest getDefaultInstanceForType() {
      return dev.vasystem.api.v2.GetVirtualAirlineRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.vasystem.api.v2.GetVirtualAirlineRequest build() {
      dev.vasystem.api.v2.GetVirtualAirlineRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.GetVirtualAirlineRequest buildPartial() {
      dev.vasystem.api.v2.GetVirtualAirlineRequest result = new dev.vasystem.api.v2.GetVirtualAirlineRequest(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.vasystem.api.v2.GetVirtualAirlineRequest) {
        return mergeFrom((dev.vasystem.api.v2.GetVirtualAirlineRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.vasystem.api.v2.GetVirtualAirlineRequest other) {
      if (other == dev.vasystem.api.v2.GetVirtualAirlineRequest.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vasystem.api.v2.GetVirtualAirlineRequest)
  }

  // @@protoc_insertion_point(class_scope:vasystem.api.v2.GetVirtualAirlineRequest)
  private static final dev.vasystem.api.v2.GetVirtualAirlineRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.vasystem.api.v2.GetVirtualAirlineRequest();
  }

  public static dev.vasystem.api.v2.GetVirtualAirlineRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVirtualAirlineRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetVirtualAirlineRequest>() {
    @java.lang.Override
    public GetVirtualAirlineRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetVirtualAirlineRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVirtualAirlineRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.vasystem.api.v2.GetVirtualAirlineRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

