// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/routes.proto

package dev.vasystem.api.v2;

public interface ListRoutesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vasystem.api.v2.ListRoutesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .vasystem.api.v2.Route routes = 1 [json_name = "routes"];</code>
   */
  java.util.List<dev.vasystem.api.v2.Route> 
      getRoutesList();
  /**
   * <code>repeated .vasystem.api.v2.Route routes = 1 [json_name = "routes"];</code>
   */
  dev.vasystem.api.v2.Route getRoutes(int index);
  /**
   * <code>repeated .vasystem.api.v2.Route routes = 1 [json_name = "routes"];</code>
   */
  int getRoutesCount();
  /**
   * <code>repeated .vasystem.api.v2.Route routes = 1 [json_name = "routes"];</code>
   */
  java.util.List<? extends dev.vasystem.api.v2.RouteOrBuilder> 
      getRoutesOrBuilderList();
  /**
   * <code>repeated .vasystem.api.v2.Route routes = 1 [json_name = "routes"];</code>
   */
  dev.vasystem.api.v2.RouteOrBuilder getRoutesOrBuilder(
      int index);

  /**
   * <pre>
   * The next_page_token value to include in a subsequent List request. When
   * paginating, all other parameters provided to List must match the call that
   * provided the page token.
   * </pre>
   *
   * <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * The next_page_token value to include in a subsequent List request. When
   * paginating, all other parameters provided to List must match the call that
   * provided the page token.
   * </pre>
   *
   * <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
