// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/routes.proto

package dev.vasystem.api.v2;

/**
 * Protobuf type {@code vasystem.api.v2.Route}
 */
public final class Route extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vasystem.api.v2.Route)
    RouteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Route.newBuilder() to construct.
  private Route(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Route() {
    id_ = "";
    icaoFlightNumber_ = "";
    daysFlown_ = java.util.Collections.emptyList();
    aircraftModels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Route();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.vasystem.api.v2.RoutesProto.internal_static_vasystem_api_v2_Route_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.vasystem.api.v2.RoutesProto.internal_static_vasystem_api_v2_Route_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.vasystem.api.v2.Route.class, dev.vasystem.api.v2.Route.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * The unique identifier for the route.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique identifier for the route.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AIRLINE_FIELD_NUMBER = 2;
  private dev.vasystem.api.v2.Airline airline_;
  /**
   * <pre>
   * The airline that operates this route.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
   * @return Whether the airline field is set.
   */
  @java.lang.Override
  public boolean hasAirline() {
    return airline_ != null;
  }
  /**
   * <pre>
   * The airline that operates this route.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
   * @return The airline.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.Airline getAirline() {
    return airline_ == null ? dev.vasystem.api.v2.Airline.getDefaultInstance() : airline_;
  }
  /**
   * <pre>
   * The airline that operates this route.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.AirlineOrBuilder getAirlineOrBuilder() {
    return getAirline();
  }

  public static final int ICAO_FLIGHT_NUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object icaoFlightNumber_;
  /**
   * <pre>
   * This does not include the airline code.
   * </pre>
   *
   * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
   * @return The icaoFlightNumber.
   */
  @java.lang.Override
  public java.lang.String getIcaoFlightNumber() {
    java.lang.Object ref = icaoFlightNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      icaoFlightNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * This does not include the airline code.
   * </pre>
   *
   * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
   * @return The bytes for icaoFlightNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIcaoFlightNumberBytes() {
    java.lang.Object ref = icaoFlightNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      icaoFlightNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_FIELD_NUMBER = 5;
  private dev.vasystem.api.v2.Airport departure_;
  /**
   * <pre>
   * The departure airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
   * @return Whether the departure field is set.
   */
  @java.lang.Override
  public boolean hasDeparture() {
    return departure_ != null;
  }
  /**
   * <pre>
   * The departure airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
   * @return The departure.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.Airport getDeparture() {
    return departure_ == null ? dev.vasystem.api.v2.Airport.getDefaultInstance() : departure_;
  }
  /**
   * <pre>
   * The departure airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.AirportOrBuilder getDepartureOrBuilder() {
    return getDeparture();
  }

  public static final int ARRIVAL_FIELD_NUMBER = 6;
  private dev.vasystem.api.v2.Airport arrival_;
  /**
   * <pre>
   * The arrival airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
   * @return Whether the arrival field is set.
   */
  @java.lang.Override
  public boolean hasArrival() {
    return arrival_ != null;
  }
  /**
   * <pre>
   * The arrival airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
   * @return The arrival.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.Airport getArrival() {
    return arrival_ == null ? dev.vasystem.api.v2.Airport.getDefaultInstance() : arrival_;
  }
  /**
   * <pre>
   * The arrival airport.
   * </pre>
   *
   * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.AirportOrBuilder getArrivalOrBuilder() {
    return getArrival();
  }

  public static final int DEPARTURE_TIME_FIELD_NUMBER = 7;
  private dev.vasystem.api.v2.TimeOfDay departureTime_;
  /**
   * <pre>
   * Departure time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
   * @return Whether the departureTime field is set.
   */
  @java.lang.Override
  public boolean hasDepartureTime() {
    return departureTime_ != null;
  }
  /**
   * <pre>
   * Departure time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
   * @return The departureTime.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.TimeOfDay getDepartureTime() {
    return departureTime_ == null ? dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : departureTime_;
  }
  /**
   * <pre>
   * Departure time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.TimeOfDayOrBuilder getDepartureTimeOrBuilder() {
    return getDepartureTime();
  }

  public static final int ARRIVAL_TIME_FIELD_NUMBER = 8;
  private dev.vasystem.api.v2.TimeOfDay arrivalTime_;
  /**
   * <pre>
   * Arrival time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
   * @return Whether the arrivalTime field is set.
   */
  @java.lang.Override
  public boolean hasArrivalTime() {
    return arrivalTime_ != null;
  }
  /**
   * <pre>
   * Arrival time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
   * @return The arrivalTime.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.TimeOfDay getArrivalTime() {
    return arrivalTime_ == null ? dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : arrivalTime_;
  }
  /**
   * <pre>
   * Arrival time is in UTC.
   * </pre>
   *
   * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.TimeOfDayOrBuilder getArrivalTimeOrBuilder() {
    return getArrivalTime();
  }

  public static final int DURATION_FIELD_NUMBER = 9;
  private com.google.protobuf.Duration duration_;
  /**
   * <pre>
   * The duration of this flight. Can also be calculated from the departure
   * and arrival times.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return duration_ != null;
  }
  /**
   * <pre>
   * The duration of this flight. Can also be calculated from the departure
   * and arrival times.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
   * @return The duration.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getDuration() {
    return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
  }
  /**
   * <pre>
   * The duration of this flight. Can also be calculated from the departure
   * and arrival times.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
    return getDuration();
  }

  public static final int DAYS_FLOWN_FIELD_NUMBER = 10;
  private java.util.List<java.lang.Integer> daysFlown_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, dev.vasystem.api.v2.DayOfWeek> daysFlown_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, dev.vasystem.api.v2.DayOfWeek>() {
            public dev.vasystem.api.v2.DayOfWeek convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              dev.vasystem.api.v2.DayOfWeek result = dev.vasystem.api.v2.DayOfWeek.valueOf(from);
              return result == null ? dev.vasystem.api.v2.DayOfWeek.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * The days of the week that this flight operates.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
   * @return A list containing the daysFlown.
   */
  @java.lang.Override
  public java.util.List<dev.vasystem.api.v2.DayOfWeek> getDaysFlownList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, dev.vasystem.api.v2.DayOfWeek>(daysFlown_, daysFlown_converter_);
  }
  /**
   * <pre>
   * The days of the week that this flight operates.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
   * @return The count of daysFlown.
   */
  @java.lang.Override
  public int getDaysFlownCount() {
    return daysFlown_.size();
  }
  /**
   * <pre>
   * The days of the week that this flight operates.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
   * @param index The index of the element to return.
   * @return The daysFlown at the given index.
   */
  @java.lang.Override
  public dev.vasystem.api.v2.DayOfWeek getDaysFlown(int index) {
    return daysFlown_converter_.convert(daysFlown_.get(index));
  }
  /**
   * <pre>
   * The days of the week that this flight operates.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
   * @return A list containing the enum numeric values on the wire for daysFlown.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getDaysFlownValueList() {
    return daysFlown_;
  }
  /**
   * <pre>
   * The days of the week that this flight operates.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of daysFlown at the given index.
   */
  @java.lang.Override
  public int getDaysFlownValue(int index) {
    return daysFlown_.get(index);
  }
  private int daysFlownMemoizedSerializedSize;

  public static final int AIRCRAFT_MODELS_FIELD_NUMBER = 11;
  private java.util.List<dev.vasystem.api.v2.AircraftModel> aircraftModels_;
  /**
   * <pre>
   * The aircraft models that operate this route.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
   */
  @java.lang.Override
  public java.util.List<dev.vasystem.api.v2.AircraftModel> getAircraftModelsList() {
    return aircraftModels_;
  }
  /**
   * <pre>
   * The aircraft models that operate this route.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.vasystem.api.v2.AircraftModelOrBuilder> 
      getAircraftModelsOrBuilderList() {
    return aircraftModels_;
  }
  /**
   * <pre>
   * The aircraft models that operate this route.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
   */
  @java.lang.Override
  public int getAircraftModelsCount() {
    return aircraftModels_.size();
  }
  /**
   * <pre>
   * The aircraft models that operate this route.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.AircraftModel getAircraftModels(int index) {
    return aircraftModels_.get(index);
  }
  /**
   * <pre>
   * The aircraft models that operate this route.
   * </pre>
   *
   * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
   */
  @java.lang.Override
  public dev.vasystem.api.v2.AircraftModelOrBuilder getAircraftModelsOrBuilder(
      int index) {
    return aircraftModels_.get(index);
  }

  public static final int ARCHIVED_FIELD_NUMBER = 16;
  private boolean archived_;
  /**
   * <pre>
   * Whether this route is archived.
   * </pre>
   *
   * <code>bool archived = 16 [json_name = "archived"];</code>
   * @return The archived.
   */
  @java.lang.Override
  public boolean getArchived() {
    return archived_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (airline_ != null) {
      output.writeMessage(2, getAirline());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(icaoFlightNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, icaoFlightNumber_);
    }
    if (departure_ != null) {
      output.writeMessage(5, getDeparture());
    }
    if (arrival_ != null) {
      output.writeMessage(6, getArrival());
    }
    if (departureTime_ != null) {
      output.writeMessage(7, getDepartureTime());
    }
    if (arrivalTime_ != null) {
      output.writeMessage(8, getArrivalTime());
    }
    if (duration_ != null) {
      output.writeMessage(9, getDuration());
    }
    if (getDaysFlownList().size() > 0) {
      output.writeUInt32NoTag(82);
      output.writeUInt32NoTag(daysFlownMemoizedSerializedSize);
    }
    for (int i = 0; i < daysFlown_.size(); i++) {
      output.writeEnumNoTag(daysFlown_.get(i));
    }
    for (int i = 0; i < aircraftModels_.size(); i++) {
      output.writeMessage(11, aircraftModels_.get(i));
    }
    if (archived_ != false) {
      output.writeBool(16, archived_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (airline_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAirline());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(icaoFlightNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, icaoFlightNumber_);
    }
    if (departure_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDeparture());
    }
    if (arrival_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getArrival());
    }
    if (departureTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDepartureTime());
    }
    if (arrivalTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getArrivalTime());
    }
    if (duration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDuration());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < daysFlown_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(daysFlown_.get(i));
      }
      size += dataSize;
      if (!getDaysFlownList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }daysFlownMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < aircraftModels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, aircraftModels_.get(i));
    }
    if (archived_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, archived_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.vasystem.api.v2.Route)) {
      return super.equals(obj);
    }
    dev.vasystem.api.v2.Route other = (dev.vasystem.api.v2.Route) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasAirline() != other.hasAirline()) return false;
    if (hasAirline()) {
      if (!getAirline()
          .equals(other.getAirline())) return false;
    }
    if (!getIcaoFlightNumber()
        .equals(other.getIcaoFlightNumber())) return false;
    if (hasDeparture() != other.hasDeparture()) return false;
    if (hasDeparture()) {
      if (!getDeparture()
          .equals(other.getDeparture())) return false;
    }
    if (hasArrival() != other.hasArrival()) return false;
    if (hasArrival()) {
      if (!getArrival()
          .equals(other.getArrival())) return false;
    }
    if (hasDepartureTime() != other.hasDepartureTime()) return false;
    if (hasDepartureTime()) {
      if (!getDepartureTime()
          .equals(other.getDepartureTime())) return false;
    }
    if (hasArrivalTime() != other.hasArrivalTime()) return false;
    if (hasArrivalTime()) {
      if (!getArrivalTime()
          .equals(other.getArrivalTime())) return false;
    }
    if (hasDuration() != other.hasDuration()) return false;
    if (hasDuration()) {
      if (!getDuration()
          .equals(other.getDuration())) return false;
    }
    if (!daysFlown_.equals(other.daysFlown_)) return false;
    if (!getAircraftModelsList()
        .equals(other.getAircraftModelsList())) return false;
    if (getArchived()
        != other.getArchived()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasAirline()) {
      hash = (37 * hash) + AIRLINE_FIELD_NUMBER;
      hash = (53 * hash) + getAirline().hashCode();
    }
    hash = (37 * hash) + ICAO_FLIGHT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getIcaoFlightNumber().hashCode();
    if (hasDeparture()) {
      hash = (37 * hash) + DEPARTURE_FIELD_NUMBER;
      hash = (53 * hash) + getDeparture().hashCode();
    }
    if (hasArrival()) {
      hash = (37 * hash) + ARRIVAL_FIELD_NUMBER;
      hash = (53 * hash) + getArrival().hashCode();
    }
    if (hasDepartureTime()) {
      hash = (37 * hash) + DEPARTURE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDepartureTime().hashCode();
    }
    if (hasArrivalTime()) {
      hash = (37 * hash) + ARRIVAL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getArrivalTime().hashCode();
    }
    if (hasDuration()) {
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration().hashCode();
    }
    if (getDaysFlownCount() > 0) {
      hash = (37 * hash) + DAYS_FLOWN_FIELD_NUMBER;
      hash = (53 * hash) + daysFlown_.hashCode();
    }
    if (getAircraftModelsCount() > 0) {
      hash = (37 * hash) + AIRCRAFT_MODELS_FIELD_NUMBER;
      hash = (53 * hash) + getAircraftModelsList().hashCode();
    }
    hash = (37 * hash) + ARCHIVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getArchived());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.vasystem.api.v2.Route parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.Route parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.vasystem.api.v2.Route parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.Route parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.Route parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.vasystem.api.v2.Route parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.vasystem.api.v2.Route prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vasystem.api.v2.Route}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vasystem.api.v2.Route)
      dev.vasystem.api.v2.RouteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.vasystem.api.v2.RoutesProto.internal_static_vasystem_api_v2_Route_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.vasystem.api.v2.RoutesProto.internal_static_vasystem_api_v2_Route_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.vasystem.api.v2.Route.class, dev.vasystem.api.v2.Route.Builder.class);
    }

    // Construct using dev.vasystem.api.v2.Route.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (airlineBuilder_ == null) {
        airline_ = null;
      } else {
        airline_ = null;
        airlineBuilder_ = null;
      }
      icaoFlightNumber_ = "";

      if (departureBuilder_ == null) {
        departure_ = null;
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }
      if (arrivalBuilder_ == null) {
        arrival_ = null;
      } else {
        arrival_ = null;
        arrivalBuilder_ = null;
      }
      if (departureTimeBuilder_ == null) {
        departureTime_ = null;
      } else {
        departureTime_ = null;
        departureTimeBuilder_ = null;
      }
      if (arrivalTimeBuilder_ == null) {
        arrivalTime_ = null;
      } else {
        arrivalTime_ = null;
        arrivalTimeBuilder_ = null;
      }
      if (durationBuilder_ == null) {
        duration_ = null;
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }
      daysFlown_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      if (aircraftModelsBuilder_ == null) {
        aircraftModels_ = java.util.Collections.emptyList();
      } else {
        aircraftModels_ = null;
        aircraftModelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      archived_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.vasystem.api.v2.RoutesProto.internal_static_vasystem_api_v2_Route_descriptor;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.Route getDefaultInstanceForType() {
      return dev.vasystem.api.v2.Route.getDefaultInstance();
    }

    @java.lang.Override
    public dev.vasystem.api.v2.Route build() {
      dev.vasystem.api.v2.Route result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.vasystem.api.v2.Route buildPartial() {
      dev.vasystem.api.v2.Route result = new dev.vasystem.api.v2.Route(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (airlineBuilder_ == null) {
        result.airline_ = airline_;
      } else {
        result.airline_ = airlineBuilder_.build();
      }
      result.icaoFlightNumber_ = icaoFlightNumber_;
      if (departureBuilder_ == null) {
        result.departure_ = departure_;
      } else {
        result.departure_ = departureBuilder_.build();
      }
      if (arrivalBuilder_ == null) {
        result.arrival_ = arrival_;
      } else {
        result.arrival_ = arrivalBuilder_.build();
      }
      if (departureTimeBuilder_ == null) {
        result.departureTime_ = departureTime_;
      } else {
        result.departureTime_ = departureTimeBuilder_.build();
      }
      if (arrivalTimeBuilder_ == null) {
        result.arrivalTime_ = arrivalTime_;
      } else {
        result.arrivalTime_ = arrivalTimeBuilder_.build();
      }
      if (durationBuilder_ == null) {
        result.duration_ = duration_;
      } else {
        result.duration_ = durationBuilder_.build();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        daysFlown_ = java.util.Collections.unmodifiableList(daysFlown_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.daysFlown_ = daysFlown_;
      if (aircraftModelsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          aircraftModels_ = java.util.Collections.unmodifiableList(aircraftModels_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.aircraftModels_ = aircraftModels_;
      } else {
        result.aircraftModels_ = aircraftModelsBuilder_.build();
      }
      result.archived_ = archived_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.vasystem.api.v2.Route) {
        return mergeFrom((dev.vasystem.api.v2.Route)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.vasystem.api.v2.Route other) {
      if (other == dev.vasystem.api.v2.Route.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasAirline()) {
        mergeAirline(other.getAirline());
      }
      if (!other.getIcaoFlightNumber().isEmpty()) {
        icaoFlightNumber_ = other.icaoFlightNumber_;
        onChanged();
      }
      if (other.hasDeparture()) {
        mergeDeparture(other.getDeparture());
      }
      if (other.hasArrival()) {
        mergeArrival(other.getArrival());
      }
      if (other.hasDepartureTime()) {
        mergeDepartureTime(other.getDepartureTime());
      }
      if (other.hasArrivalTime()) {
        mergeArrivalTime(other.getArrivalTime());
      }
      if (other.hasDuration()) {
        mergeDuration(other.getDuration());
      }
      if (!other.daysFlown_.isEmpty()) {
        if (daysFlown_.isEmpty()) {
          daysFlown_ = other.daysFlown_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDaysFlownIsMutable();
          daysFlown_.addAll(other.daysFlown_);
        }
        onChanged();
      }
      if (aircraftModelsBuilder_ == null) {
        if (!other.aircraftModels_.isEmpty()) {
          if (aircraftModels_.isEmpty()) {
            aircraftModels_ = other.aircraftModels_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAircraftModelsIsMutable();
            aircraftModels_.addAll(other.aircraftModels_);
          }
          onChanged();
        }
      } else {
        if (!other.aircraftModels_.isEmpty()) {
          if (aircraftModelsBuilder_.isEmpty()) {
            aircraftModelsBuilder_.dispose();
            aircraftModelsBuilder_ = null;
            aircraftModels_ = other.aircraftModels_;
            bitField0_ = (bitField0_ & ~0x00000002);
            aircraftModelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAircraftModelsFieldBuilder() : null;
          } else {
            aircraftModelsBuilder_.addAllMessages(other.aircraftModels_);
          }
        }
      }
      if (other.getArchived() != false) {
        setArchived(other.getArchived());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAirlineFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              icaoFlightNumber_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 42: {
              input.readMessage(
                  getDepartureFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getArrivalFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getDepartureTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getArrivalTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getDurationFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 74
            case 80: {
              int tmpRaw = input.readEnum();
              ensureDaysFlownIsMutable();
              daysFlown_.add(tmpRaw);
              break;
            } // case 80
            case 82: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureDaysFlownIsMutable();
                daysFlown_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 82
            case 90: {
              dev.vasystem.api.v2.AircraftModel m =
                  input.readMessage(
                      dev.vasystem.api.v2.AircraftModel.parser(),
                      extensionRegistry);
              if (aircraftModelsBuilder_ == null) {
                ensureAircraftModelsIsMutable();
                aircraftModels_.add(m);
              } else {
                aircraftModelsBuilder_.addMessage(m);
              }
              break;
            } // case 90
            case 128: {
              archived_ = input.readBool();

              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * The unique identifier for the route.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier for the route.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique identifier for the route.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier for the route.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique identifier for the route.
     * </pre>
     *
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private dev.vasystem.api.v2.Airline airline_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airline, dev.vasystem.api.v2.Airline.Builder, dev.vasystem.api.v2.AirlineOrBuilder> airlineBuilder_;
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     * @return Whether the airline field is set.
     */
    public boolean hasAirline() {
      return airlineBuilder_ != null || airline_ != null;
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     * @return The airline.
     */
    public dev.vasystem.api.v2.Airline getAirline() {
      if (airlineBuilder_ == null) {
        return airline_ == null ? dev.vasystem.api.v2.Airline.getDefaultInstance() : airline_;
      } else {
        return airlineBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public Builder setAirline(dev.vasystem.api.v2.Airline value) {
      if (airlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        airline_ = value;
        onChanged();
      } else {
        airlineBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public Builder setAirline(
        dev.vasystem.api.v2.Airline.Builder builderForValue) {
      if (airlineBuilder_ == null) {
        airline_ = builderForValue.build();
        onChanged();
      } else {
        airlineBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public Builder mergeAirline(dev.vasystem.api.v2.Airline value) {
      if (airlineBuilder_ == null) {
        if (airline_ != null) {
          airline_ =
            dev.vasystem.api.v2.Airline.newBuilder(airline_).mergeFrom(value).buildPartial();
        } else {
          airline_ = value;
        }
        onChanged();
      } else {
        airlineBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public Builder clearAirline() {
      if (airlineBuilder_ == null) {
        airline_ = null;
        onChanged();
      } else {
        airline_ = null;
        airlineBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public dev.vasystem.api.v2.Airline.Builder getAirlineBuilder() {
      
      onChanged();
      return getAirlineFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    public dev.vasystem.api.v2.AirlineOrBuilder getAirlineOrBuilder() {
      if (airlineBuilder_ != null) {
        return airlineBuilder_.getMessageOrBuilder();
      } else {
        return airline_ == null ?
            dev.vasystem.api.v2.Airline.getDefaultInstance() : airline_;
      }
    }
    /**
     * <pre>
     * The airline that operates this route.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airline airline = 2 [json_name = "airline"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airline, dev.vasystem.api.v2.Airline.Builder, dev.vasystem.api.v2.AirlineOrBuilder> 
        getAirlineFieldBuilder() {
      if (airlineBuilder_ == null) {
        airlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.vasystem.api.v2.Airline, dev.vasystem.api.v2.Airline.Builder, dev.vasystem.api.v2.AirlineOrBuilder>(
                getAirline(),
                getParentForChildren(),
                isClean());
        airline_ = null;
      }
      return airlineBuilder_;
    }

    private java.lang.Object icaoFlightNumber_ = "";
    /**
     * <pre>
     * This does not include the airline code.
     * </pre>
     *
     * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
     * @return The icaoFlightNumber.
     */
    public java.lang.String getIcaoFlightNumber() {
      java.lang.Object ref = icaoFlightNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        icaoFlightNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * This does not include the airline code.
     * </pre>
     *
     * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
     * @return The bytes for icaoFlightNumber.
     */
    public com.google.protobuf.ByteString
        getIcaoFlightNumberBytes() {
      java.lang.Object ref = icaoFlightNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icaoFlightNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * This does not include the airline code.
     * </pre>
     *
     * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
     * @param value The icaoFlightNumber to set.
     * @return This builder for chaining.
     */
    public Builder setIcaoFlightNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      icaoFlightNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This does not include the airline code.
     * </pre>
     *
     * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIcaoFlightNumber() {
      
      icaoFlightNumber_ = getDefaultInstance().getIcaoFlightNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This does not include the airline code.
     * </pre>
     *
     * <code>string icao_flight_number = 3 [json_name = "icaoFlightNumber"];</code>
     * @param value The bytes for icaoFlightNumber to set.
     * @return This builder for chaining.
     */
    public Builder setIcaoFlightNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      icaoFlightNumber_ = value;
      onChanged();
      return this;
    }

    private dev.vasystem.api.v2.Airport departure_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder> departureBuilder_;
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     * @return Whether the departure field is set.
     */
    public boolean hasDeparture() {
      return departureBuilder_ != null || departure_ != null;
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     * @return The departure.
     */
    public dev.vasystem.api.v2.Airport getDeparture() {
      if (departureBuilder_ == null) {
        return departure_ == null ? dev.vasystem.api.v2.Airport.getDefaultInstance() : departure_;
      } else {
        return departureBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public Builder setDeparture(dev.vasystem.api.v2.Airport value) {
      if (departureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        departure_ = value;
        onChanged();
      } else {
        departureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public Builder setDeparture(
        dev.vasystem.api.v2.Airport.Builder builderForValue) {
      if (departureBuilder_ == null) {
        departure_ = builderForValue.build();
        onChanged();
      } else {
        departureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public Builder mergeDeparture(dev.vasystem.api.v2.Airport value) {
      if (departureBuilder_ == null) {
        if (departure_ != null) {
          departure_ =
            dev.vasystem.api.v2.Airport.newBuilder(departure_).mergeFrom(value).buildPartial();
        } else {
          departure_ = value;
        }
        onChanged();
      } else {
        departureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public Builder clearDeparture() {
      if (departureBuilder_ == null) {
        departure_ = null;
        onChanged();
      } else {
        departure_ = null;
        departureBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public dev.vasystem.api.v2.Airport.Builder getDepartureBuilder() {
      
      onChanged();
      return getDepartureFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    public dev.vasystem.api.v2.AirportOrBuilder getDepartureOrBuilder() {
      if (departureBuilder_ != null) {
        return departureBuilder_.getMessageOrBuilder();
      } else {
        return departure_ == null ?
            dev.vasystem.api.v2.Airport.getDefaultInstance() : departure_;
      }
    }
    /**
     * <pre>
     * The departure airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport departure = 5 [json_name = "departure"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder> 
        getDepartureFieldBuilder() {
      if (departureBuilder_ == null) {
        departureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder>(
                getDeparture(),
                getParentForChildren(),
                isClean());
        departure_ = null;
      }
      return departureBuilder_;
    }

    private dev.vasystem.api.v2.Airport arrival_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder> arrivalBuilder_;
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     * @return Whether the arrival field is set.
     */
    public boolean hasArrival() {
      return arrivalBuilder_ != null || arrival_ != null;
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     * @return The arrival.
     */
    public dev.vasystem.api.v2.Airport getArrival() {
      if (arrivalBuilder_ == null) {
        return arrival_ == null ? dev.vasystem.api.v2.Airport.getDefaultInstance() : arrival_;
      } else {
        return arrivalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public Builder setArrival(dev.vasystem.api.v2.Airport value) {
      if (arrivalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        arrival_ = value;
        onChanged();
      } else {
        arrivalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public Builder setArrival(
        dev.vasystem.api.v2.Airport.Builder builderForValue) {
      if (arrivalBuilder_ == null) {
        arrival_ = builderForValue.build();
        onChanged();
      } else {
        arrivalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public Builder mergeArrival(dev.vasystem.api.v2.Airport value) {
      if (arrivalBuilder_ == null) {
        if (arrival_ != null) {
          arrival_ =
            dev.vasystem.api.v2.Airport.newBuilder(arrival_).mergeFrom(value).buildPartial();
        } else {
          arrival_ = value;
        }
        onChanged();
      } else {
        arrivalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public Builder clearArrival() {
      if (arrivalBuilder_ == null) {
        arrival_ = null;
        onChanged();
      } else {
        arrival_ = null;
        arrivalBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public dev.vasystem.api.v2.Airport.Builder getArrivalBuilder() {
      
      onChanged();
      return getArrivalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    public dev.vasystem.api.v2.AirportOrBuilder getArrivalOrBuilder() {
      if (arrivalBuilder_ != null) {
        return arrivalBuilder_.getMessageOrBuilder();
      } else {
        return arrival_ == null ?
            dev.vasystem.api.v2.Airport.getDefaultInstance() : arrival_;
      }
    }
    /**
     * <pre>
     * The arrival airport.
     * </pre>
     *
     * <code>.vasystem.api.v2.Airport arrival = 6 [json_name = "arrival"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder> 
        getArrivalFieldBuilder() {
      if (arrivalBuilder_ == null) {
        arrivalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.vasystem.api.v2.Airport, dev.vasystem.api.v2.Airport.Builder, dev.vasystem.api.v2.AirportOrBuilder>(
                getArrival(),
                getParentForChildren(),
                isClean());
        arrival_ = null;
      }
      return arrivalBuilder_;
    }

    private dev.vasystem.api.v2.TimeOfDay departureTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder> departureTimeBuilder_;
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     * @return Whether the departureTime field is set.
     */
    public boolean hasDepartureTime() {
      return departureTimeBuilder_ != null || departureTime_ != null;
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     * @return The departureTime.
     */
    public dev.vasystem.api.v2.TimeOfDay getDepartureTime() {
      if (departureTimeBuilder_ == null) {
        return departureTime_ == null ? dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : departureTime_;
      } else {
        return departureTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public Builder setDepartureTime(dev.vasystem.api.v2.TimeOfDay value) {
      if (departureTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        departureTime_ = value;
        onChanged();
      } else {
        departureTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public Builder setDepartureTime(
        dev.vasystem.api.v2.TimeOfDay.Builder builderForValue) {
      if (departureTimeBuilder_ == null) {
        departureTime_ = builderForValue.build();
        onChanged();
      } else {
        departureTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public Builder mergeDepartureTime(dev.vasystem.api.v2.TimeOfDay value) {
      if (departureTimeBuilder_ == null) {
        if (departureTime_ != null) {
          departureTime_ =
            dev.vasystem.api.v2.TimeOfDay.newBuilder(departureTime_).mergeFrom(value).buildPartial();
        } else {
          departureTime_ = value;
        }
        onChanged();
      } else {
        departureTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public Builder clearDepartureTime() {
      if (departureTimeBuilder_ == null) {
        departureTime_ = null;
        onChanged();
      } else {
        departureTime_ = null;
        departureTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public dev.vasystem.api.v2.TimeOfDay.Builder getDepartureTimeBuilder() {
      
      onChanged();
      return getDepartureTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    public dev.vasystem.api.v2.TimeOfDayOrBuilder getDepartureTimeOrBuilder() {
      if (departureTimeBuilder_ != null) {
        return departureTimeBuilder_.getMessageOrBuilder();
      } else {
        return departureTime_ == null ?
            dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : departureTime_;
      }
    }
    /**
     * <pre>
     * Departure time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay departure_time = 7 [json_name = "departureTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder> 
        getDepartureTimeFieldBuilder() {
      if (departureTimeBuilder_ == null) {
        departureTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder>(
                getDepartureTime(),
                getParentForChildren(),
                isClean());
        departureTime_ = null;
      }
      return departureTimeBuilder_;
    }

    private dev.vasystem.api.v2.TimeOfDay arrivalTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder> arrivalTimeBuilder_;
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     * @return Whether the arrivalTime field is set.
     */
    public boolean hasArrivalTime() {
      return arrivalTimeBuilder_ != null || arrivalTime_ != null;
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     * @return The arrivalTime.
     */
    public dev.vasystem.api.v2.TimeOfDay getArrivalTime() {
      if (arrivalTimeBuilder_ == null) {
        return arrivalTime_ == null ? dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : arrivalTime_;
      } else {
        return arrivalTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public Builder setArrivalTime(dev.vasystem.api.v2.TimeOfDay value) {
      if (arrivalTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        arrivalTime_ = value;
        onChanged();
      } else {
        arrivalTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public Builder setArrivalTime(
        dev.vasystem.api.v2.TimeOfDay.Builder builderForValue) {
      if (arrivalTimeBuilder_ == null) {
        arrivalTime_ = builderForValue.build();
        onChanged();
      } else {
        arrivalTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public Builder mergeArrivalTime(dev.vasystem.api.v2.TimeOfDay value) {
      if (arrivalTimeBuilder_ == null) {
        if (arrivalTime_ != null) {
          arrivalTime_ =
            dev.vasystem.api.v2.TimeOfDay.newBuilder(arrivalTime_).mergeFrom(value).buildPartial();
        } else {
          arrivalTime_ = value;
        }
        onChanged();
      } else {
        arrivalTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public Builder clearArrivalTime() {
      if (arrivalTimeBuilder_ == null) {
        arrivalTime_ = null;
        onChanged();
      } else {
        arrivalTime_ = null;
        arrivalTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public dev.vasystem.api.v2.TimeOfDay.Builder getArrivalTimeBuilder() {
      
      onChanged();
      return getArrivalTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    public dev.vasystem.api.v2.TimeOfDayOrBuilder getArrivalTimeOrBuilder() {
      if (arrivalTimeBuilder_ != null) {
        return arrivalTimeBuilder_.getMessageOrBuilder();
      } else {
        return arrivalTime_ == null ?
            dev.vasystem.api.v2.TimeOfDay.getDefaultInstance() : arrivalTime_;
      }
    }
    /**
     * <pre>
     * Arrival time is in UTC.
     * </pre>
     *
     * <code>.vasystem.api.v2.TimeOfDay arrival_time = 8 [json_name = "arrivalTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder> 
        getArrivalTimeFieldBuilder() {
      if (arrivalTimeBuilder_ == null) {
        arrivalTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dev.vasystem.api.v2.TimeOfDay, dev.vasystem.api.v2.TimeOfDay.Builder, dev.vasystem.api.v2.TimeOfDayOrBuilder>(
                getArrivalTime(),
                getParentForChildren(),
                isClean());
        arrivalTime_ = null;
      }
      return arrivalTimeBuilder_;
    }

    private com.google.protobuf.Duration duration_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     * @return Whether the duration field is set.
     */
    public boolean hasDuration() {
      return durationBuilder_ != null || duration_ != null;
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     * @return The duration.
     */
    public com.google.protobuf.Duration getDuration() {
      if (durationBuilder_ == null) {
        return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
      } else {
        return durationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public Builder setDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        duration_ = value;
        onChanged();
      } else {
        durationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public Builder setDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (durationBuilder_ == null) {
        duration_ = builderForValue.build();
        onChanged();
      } else {
        durationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public Builder mergeDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (duration_ != null) {
          duration_ =
            com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
        } else {
          duration_ = value;
        }
        onChanged();
      } else {
        durationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public Builder clearDuration() {
      if (durationBuilder_ == null) {
        duration_ = null;
        onChanged();
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public com.google.protobuf.Duration.Builder getDurationBuilder() {
      
      onChanged();
      return getDurationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      if (durationBuilder_ != null) {
        return durationBuilder_.getMessageOrBuilder();
      } else {
        return duration_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : duration_;
      }
    }
    /**
     * <pre>
     * The duration of this flight. Can also be calculated from the departure
     * and arrival times.
     * </pre>
     *
     * <code>.google.protobuf.Duration duration = 9 [json_name = "duration"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getDurationFieldBuilder() {
      if (durationBuilder_ == null) {
        durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getDuration(),
                getParentForChildren(),
                isClean());
        duration_ = null;
      }
      return durationBuilder_;
    }

    private java.util.List<java.lang.Integer> daysFlown_ =
      java.util.Collections.emptyList();
    private void ensureDaysFlownIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        daysFlown_ = new java.util.ArrayList<java.lang.Integer>(daysFlown_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @return A list containing the daysFlown.
     */
    public java.util.List<dev.vasystem.api.v2.DayOfWeek> getDaysFlownList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, dev.vasystem.api.v2.DayOfWeek>(daysFlown_, daysFlown_converter_);
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @return The count of daysFlown.
     */
    public int getDaysFlownCount() {
      return daysFlown_.size();
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param index The index of the element to return.
     * @return The daysFlown at the given index.
     */
    public dev.vasystem.api.v2.DayOfWeek getDaysFlown(int index) {
      return daysFlown_converter_.convert(daysFlown_.get(index));
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param index The index to set the value at.
     * @param value The daysFlown to set.
     * @return This builder for chaining.
     */
    public Builder setDaysFlown(
        int index, dev.vasystem.api.v2.DayOfWeek value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDaysFlownIsMutable();
      daysFlown_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param value The daysFlown to add.
     * @return This builder for chaining.
     */
    public Builder addDaysFlown(dev.vasystem.api.v2.DayOfWeek value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDaysFlownIsMutable();
      daysFlown_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param values The daysFlown to add.
     * @return This builder for chaining.
     */
    public Builder addAllDaysFlown(
        java.lang.Iterable<? extends dev.vasystem.api.v2.DayOfWeek> values) {
      ensureDaysFlownIsMutable();
      for (dev.vasystem.api.v2.DayOfWeek value : values) {
        daysFlown_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDaysFlown() {
      daysFlown_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @return A list containing the enum numeric values on the wire for daysFlown.
     */
    public java.util.List<java.lang.Integer>
    getDaysFlownValueList() {
      return java.util.Collections.unmodifiableList(daysFlown_);
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of daysFlown at the given index.
     */
    public int getDaysFlownValue(int index) {
      return daysFlown_.get(index);
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for daysFlown to set.
     * @return This builder for chaining.
     */
    public Builder setDaysFlownValue(
        int index, int value) {
      ensureDaysFlownIsMutable();
      daysFlown_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param value The enum numeric value on the wire for daysFlown to add.
     * @return This builder for chaining.
     */
    public Builder addDaysFlownValue(int value) {
      ensureDaysFlownIsMutable();
      daysFlown_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The days of the week that this flight operates.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.DayOfWeek days_flown = 10 [json_name = "daysFlown"];</code>
     * @param values The enum numeric values on the wire for daysFlown to add.
     * @return This builder for chaining.
     */
    public Builder addAllDaysFlownValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureDaysFlownIsMutable();
      for (int value : values) {
        daysFlown_.add(value);
      }
      onChanged();
      return this;
    }

    private java.util.List<dev.vasystem.api.v2.AircraftModel> aircraftModels_ =
      java.util.Collections.emptyList();
    private void ensureAircraftModelsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        aircraftModels_ = new java.util.ArrayList<dev.vasystem.api.v2.AircraftModel>(aircraftModels_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.vasystem.api.v2.AircraftModel, dev.vasystem.api.v2.AircraftModel.Builder, dev.vasystem.api.v2.AircraftModelOrBuilder> aircraftModelsBuilder_;

    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public java.util.List<dev.vasystem.api.v2.AircraftModel> getAircraftModelsList() {
      if (aircraftModelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aircraftModels_);
      } else {
        return aircraftModelsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public int getAircraftModelsCount() {
      if (aircraftModelsBuilder_ == null) {
        return aircraftModels_.size();
      } else {
        return aircraftModelsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public dev.vasystem.api.v2.AircraftModel getAircraftModels(int index) {
      if (aircraftModelsBuilder_ == null) {
        return aircraftModels_.get(index);
      } else {
        return aircraftModelsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder setAircraftModels(
        int index, dev.vasystem.api.v2.AircraftModel value) {
      if (aircraftModelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAircraftModelsIsMutable();
        aircraftModels_.set(index, value);
        onChanged();
      } else {
        aircraftModelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder setAircraftModels(
        int index, dev.vasystem.api.v2.AircraftModel.Builder builderForValue) {
      if (aircraftModelsBuilder_ == null) {
        ensureAircraftModelsIsMutable();
        aircraftModels_.set(index, builderForValue.build());
        onChanged();
      } else {
        aircraftModelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder addAircraftModels(dev.vasystem.api.v2.AircraftModel value) {
      if (aircraftModelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAircraftModelsIsMutable();
        aircraftModels_.add(value);
        onChanged();
      } else {
        aircraftModelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder addAircraftModels(
        int index, dev.vasystem.api.v2.AircraftModel value) {
      if (aircraftModelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAircraftModelsIsMutable();
        aircraftModels_.add(index, value);
        onChanged();
      } else {
        aircraftModelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder addAircraftModels(
        dev.vasystem.api.v2.AircraftModel.Builder builderForValue) {
      if (aircraftModelsBuilder_ == null) {
        ensureAircraftModelsIsMutable();
        aircraftModels_.add(builderForValue.build());
        onChanged();
      } else {
        aircraftModelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder addAircraftModels(
        int index, dev.vasystem.api.v2.AircraftModel.Builder builderForValue) {
      if (aircraftModelsBuilder_ == null) {
        ensureAircraftModelsIsMutable();
        aircraftModels_.add(index, builderForValue.build());
        onChanged();
      } else {
        aircraftModelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder addAllAircraftModels(
        java.lang.Iterable<? extends dev.vasystem.api.v2.AircraftModel> values) {
      if (aircraftModelsBuilder_ == null) {
        ensureAircraftModelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aircraftModels_);
        onChanged();
      } else {
        aircraftModelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder clearAircraftModels() {
      if (aircraftModelsBuilder_ == null) {
        aircraftModels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        aircraftModelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public Builder removeAircraftModels(int index) {
      if (aircraftModelsBuilder_ == null) {
        ensureAircraftModelsIsMutable();
        aircraftModels_.remove(index);
        onChanged();
      } else {
        aircraftModelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public dev.vasystem.api.v2.AircraftModel.Builder getAircraftModelsBuilder(
        int index) {
      return getAircraftModelsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public dev.vasystem.api.v2.AircraftModelOrBuilder getAircraftModelsOrBuilder(
        int index) {
      if (aircraftModelsBuilder_ == null) {
        return aircraftModels_.get(index);  } else {
        return aircraftModelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public java.util.List<? extends dev.vasystem.api.v2.AircraftModelOrBuilder> 
         getAircraftModelsOrBuilderList() {
      if (aircraftModelsBuilder_ != null) {
        return aircraftModelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aircraftModels_);
      }
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public dev.vasystem.api.v2.AircraftModel.Builder addAircraftModelsBuilder() {
      return getAircraftModelsFieldBuilder().addBuilder(
          dev.vasystem.api.v2.AircraftModel.getDefaultInstance());
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public dev.vasystem.api.v2.AircraftModel.Builder addAircraftModelsBuilder(
        int index) {
      return getAircraftModelsFieldBuilder().addBuilder(
          index, dev.vasystem.api.v2.AircraftModel.getDefaultInstance());
    }
    /**
     * <pre>
     * The aircraft models that operate this route.
     * </pre>
     *
     * <code>repeated .vasystem.api.v2.AircraftModel aircraft_models = 11 [json_name = "aircraftModels"];</code>
     */
    public java.util.List<dev.vasystem.api.v2.AircraftModel.Builder> 
         getAircraftModelsBuilderList() {
      return getAircraftModelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dev.vasystem.api.v2.AircraftModel, dev.vasystem.api.v2.AircraftModel.Builder, dev.vasystem.api.v2.AircraftModelOrBuilder> 
        getAircraftModelsFieldBuilder() {
      if (aircraftModelsBuilder_ == null) {
        aircraftModelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dev.vasystem.api.v2.AircraftModel, dev.vasystem.api.v2.AircraftModel.Builder, dev.vasystem.api.v2.AircraftModelOrBuilder>(
                aircraftModels_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        aircraftModels_ = null;
      }
      return aircraftModelsBuilder_;
    }

    private boolean archived_ ;
    /**
     * <pre>
     * Whether this route is archived.
     * </pre>
     *
     * <code>bool archived = 16 [json_name = "archived"];</code>
     * @return The archived.
     */
    @java.lang.Override
    public boolean getArchived() {
      return archived_;
    }
    /**
     * <pre>
     * Whether this route is archived.
     * </pre>
     *
     * <code>bool archived = 16 [json_name = "archived"];</code>
     * @param value The archived to set.
     * @return This builder for chaining.
     */
    public Builder setArchived(boolean value) {
      
      archived_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this route is archived.
     * </pre>
     *
     * <code>bool archived = 16 [json_name = "archived"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArchived() {
      
      archived_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vasystem.api.v2.Route)
  }

  // @@protoc_insertion_point(class_scope:vasystem.api.v2.Route)
  private static final dev.vasystem.api.v2.Route DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.vasystem.api.v2.Route();
  }

  public static dev.vasystem.api.v2.Route getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Route>
      PARSER = new com.google.protobuf.AbstractParser<Route>() {
    @java.lang.Override
    public Route parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Route> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Route> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.vasystem.api.v2.Route getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

