// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vasystem/api/v2/virtual_airlines.proto

package dev.vasystem.api.v2;

public final class VirtualAirlinesProto {
  private VirtualAirlinesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vasystem_api_v2_GetVirtualAirlineRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vasystem_api_v2_GetVirtualAirlineResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vasystem_api_v2_GetVirtualAirlineResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vasystem_api_v2_VirtualAirline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vasystem_api_v2_VirtualAirline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&vasystem/api/v2/virtual_airlines.proto" +
      "\022\017vasystem.api.v2\"\032\n\030GetVirtualAirlineRe" +
      "quest\"e\n\031GetVirtualAirlineResponse\022H\n\017vi" +
      "rtual_airline\030\001 \001(\0132\037.vasystem.api.v2.Vi" +
      "rtualAirlineR\016virtualAirline\"6\n\016VirtualA" +
      "irline\022\022\n\004name\030\001 \001(\tR\004name\022\020\n\003url\030\002 \001(\tR" +
      "\003url2\206\001\n\026VirtualAirlinesService\022l\n\021GetVi" +
      "rtualAirline\022).vasystem.api.v2.GetVirtua" +
      "lAirlineRequest\032*.vasystem.api.v2.GetVir" +
      "tualAirlineResponse\"\000B\300\001\n\023dev.vasystem.a" +
      "pi.v2B\024VirtualAirlinesProtoP\001Z5github.co" +
      "m/vasystem/api/grpc/go/vasystem/api/v2;a" +
      "piv2\242\002\003VAX\252\002\017Vasystem.Api.V2\312\002\017Vasystem\\" +
      "Api\\V2\342\002\033Vasystem\\Api\\V2\\GPBMetadata\352\002\021V" +
      "asystem::Api::V2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vasystem_api_v2_GetVirtualAirlineRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vasystem_api_v2_GetVirtualAirlineRequest_descriptor,
        new java.lang.String[] { });
    internal_static_vasystem_api_v2_GetVirtualAirlineResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vasystem_api_v2_GetVirtualAirlineResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vasystem_api_v2_GetVirtualAirlineResponse_descriptor,
        new java.lang.String[] { "VirtualAirline", });
    internal_static_vasystem_api_v2_VirtualAirline_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vasystem_api_v2_VirtualAirline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vasystem_api_v2_VirtualAirline_descriptor,
        new java.lang.String[] { "Name", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
