name: Lint

on:
  push:
    branches:
      - main

jobs:
  buf:
    runs-on: ubuntu-latest
    name: Lint protos
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
